sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
  - sudo apt-get install -qq cppcheck
script:
  - cd src/identifier
  cppcheck src/identifier.c
  - make
