#include "unity.h"
#include "unity_fixture.h"

TEST_GROUP_RUNNER(BLOWFISH)
{
  RUN_TEST_CASE(BLOWFISH, TestBLOWFISH_ENC_128);
  RUN_TEST_CASE(BLOWFISH, TestBLOWFISH_DEC_128);

  RUN_TEST_CASE(BLOWFISH, TestBLOWFISH_ENC_192);
  RUN_TEST_CASE(BLOWFISH, TestBLOWFISH_DEC_192);

  RUN_TEST_CASE(BLOWFISH, TestBLOWFISH_ENC_256);
  RUN_TEST_CASE(BLOWFISH, TestBLOWFISH_DEC_256);
}
